
""" Configuration Defaults """
DEBUG = True
FLATPAGES_EXTENSION = '.md'
FLATPAGES_ROOT = 'src'
FLATPAGES_AUTO_RELOAD = True
#FLATPAGES_MARKDOWN_EXTENSIONS = ['fenced_code']
FREEZER_DESTINATION = 'build'
